### ISSUE TITLE
Tracking sketch dependencies

### ISSUE THREAD

**Issue by rbpasker** [arduino/arduino-ide#1595]
### Describe the request

Need to be able to specify the exact library that a sketch depends on. 

For example if I see '#include TM1637Dispaly.h' at the top of a sketch, and search the Library Manager, it returns 11 different results, only one of which is correct.  

node has npm
python has `pip install -requirements`

### Describe the current behavior

have to search the library till you find the correct one

### Arduino IDE version

2.0

### Operating system

macOS

### Operating system version

10.15

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the feature was still missing when using the latest [nightly build](https://github.com/arduino/arduino-ide#nightly-builds)
- [X] My request contains all necessary details
